world: 'world' # the name of the overworld world. Will also set the players sleeping percentage gamerule to 101 so we can handle sleeping.
votes-required: 0.5 # max players * votes-required = required votes, so 0.5 = 50% of max players
reset-weather: true
ticks-before-sending-new-actionbar: 5 # This is to override the X/Y sleeping actionbar.
suppress-vanilla-actionbar: true
smooth:
  enabled: true
  add-ticks: 50 # How many ticks to add to the time.
  run-ticks: 2 # Intervals to run the runnable in ticks
action-bar:
  enabled: true
  bar: '<white>%player% has slept. %votes%/%required% votes to skip night.'
  skipping: '<white>Skipping the night...'
